using RData.LitJson;

public class JwtSession
{
    public string id;
    public string provider;

    [JsonIgnore] public const string kProviderLocal = "local";
    [JsonIgnore] public const string kProviderTest = "test"; // Tokens generated by unit/integration tests must not be accepted
}
